name: learn-github-actions
on: [push]
jobs:
  proves_directoris:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pwd
      - run: ls -la
      - run: cd ./Muntanyes/
      - run: ls -la
      - run: mkdocs build
      - run: ls -la 
